/** IPC channel names shared by the main process and the preload bridge. */
export const IPC = {
  capture: 'shotr:capture',
  getHotkeys: 'shotr:getHotkeys',
  setHotkey: 'shotr:setHotkey',
  getPermission: 'shotr:getPermission',
  requestAccess: 'shotr:requestAccess',
  getBackground: 'shotr:getBackground',
  setBackground: 'shotr:setBackground',
  openSettings: 'shotr:openSettings',
  closeControl: 'shotr:closeControl',
  minimizeControl: 'shotr:minimizeControl',
  resizeControl: 'shotr:resizeControl',
  regionImage: 'shotr:regionImage',
  regionReady: 'shotr:regionReady',
  regionComplete: 'shotr:regionComplete',
  regionCancel: 'shotr:regionCancel',
  listWindows: 'shotr:listWindows',
  captureWindow: 'shotr:captureWindow',
  pickerCancel: 'shotr:pickerCancel',
  editorImage: 'shotr:editorImage',
  copyImage: 'shotr:copyImage',
  saveImage: 'shotr:saveImage',
  // Web-page capture (UI-driven CLI engine)
  webOpen: 'shotr:webOpen',
  webListProjects: 'shotr:webListProjects',
  webGetProject: 'shotr:webGetProject',
  webSaveProject: 'shotr:webSaveProject',
  webDeleteProject: 'shotr:webDeleteProject',
  webRun: 'shotr:webRun',
  webProgress: 'shotr:webProgress',
  webManualStart: 'shotr:webManualStart',
  webManualSave: 'shotr:webManualSave',
  webManualCancel: 'shotr:webManualCancel',
  webSessionStatus: 'shotr:webSessionStatus',
  webClearSession: 'shotr:webClearSession',
  webExportYaml: 'shotr:webExportYaml',
  webImportYaml: 'shotr:webImportYaml',
  webOpenReport: 'shotr:webOpenReport',
  webOpenFolder: 'shotr:webOpenFolder',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
